### ISSUE TITLE
Command line errors output don't reflect the editor

### ISSUE THREAD

**Issue by xshapira** [microsoft/vscode-mypy#188]
Similar to this issue #174. Despite trying all the suggested configurations, I couldn't get it to work. I spent a few good hours trying to figure it out with no success. I think you should've only deprecated ﻿`"python.linting.mypyEnabled": true` when the Mypy Type Checker extension worked properly. It seems there's no straightforward way to configure the extension to read mypy config from a ﻿`pyproject.toml` file.

![CleanShot 2023-10-30 at 19 28 43@2x](https://github.com/microsoft/vscode-mypy/assets/48856190/9aba553d-43c8-43c8-b244-c7ae9b821544)

I'm using the pre-release version of the mypy extension. My workspace settings are the following:
```json
{
	// Python
  "python.defaultInterpreterPath": "${workspaceFolder}/.venv/bin/python",
  "mypy-type-checker.path": ["${workspaceFolder}/.venv/bin/mypy"],
  "mypy-type-checker.args": [
    "--config-file",
    "${workspaceFolder}/pyproject.toml"
  ],
  "mypy-type-checker.preferDaemon": false,
}
```
And here is my `pyproject.toml`:
```toml
[tool.poetry]
name = "app"
version = "0.1.0"
description = ""
authors = ["Admin <admin@example.com>"]

[tool.poetry.dependencies]
python = "^3.12"
requests = "^2.31.0"

[tool.poetry.group.dev.dependencies]
ruff = "^0.1.3"
mypy = "^1.6.1"
pre-commit = "^3.5.0"
types-requests = "^2.31.0.9"

[tool.mypy]
disallow_untyped_defs = true
disallow_any_unimported = true
no_implicit_optional = true
no_implicit_reexport = true
check_untyped_defs = true
strict_equality = true
warn_unused_ignores = true
warn_redundant_casts = true
warn_return_any = true
show_error_codes = true

[tool.ruff]
line-length = 88
exclude = [
    '.git',
    '__pycache__',
    '__init__.py',
    '.mypy_cache',
    '.pytest_cache',
]
select = [
    "E",  # pycodestyle errors
    "W",  # pycodestyle warnings
    "F",  # pyflakes
    "I",  # isort
    "C",  # flake8-comprehensions
    "B",  # flake8-bugbear
    "UP",  # pyupgrade
]
ignore = [
    "E501",  # line too long
    "C901",  # Comprehension is too complex (11 > 10)
    "W191", # indentation contains tabs
]
unfixable = ["F841"]

[tool.ruff.pyupgrade]
# Preserve types, even if a file imports `from __future__ import annotations`.
keep-runtime-typing = true

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
```
